#include "cuda/codegen.hpp"

#include <algorithm>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <sstream>

namespace minicompiler::cuda {
namespace {

// The exact bit pattern, so the kernel uses the same float as the IR (this
// also covers infinities and NaN), with the decimal value as a comment.
std::string float_literal(float v) {
	std::uint32_t bits;
	std::memcpy(&bits, &v, sizeof bits);
	char buf[80];
	std::snprintf(buf, sizeof buf, "__uint_as_float(0x%08xu);  // %.9g", static_cast<unsigned>(bits),
	              static_cast<double>(v));
	return buf;
}

std::string op_expr(OpKind op, const std::string& a, const std::string& b) {
	switch (op) {
		case OpKind::Neg: return "-" + a;
		case OpKind::Exp: return "expf(" + a + ")";
		case OpKind::Log: return "logf(" + a + ")";
		case OpKind::Sqrt: return "sqrtf(" + a + ")";
		case OpKind::Relu: return "fmaxf(" + a + ", 0.0f)";
		case OpKind::Sigmoid: return "1.0f / (1.0f + expf(-" + a + "))";
		case OpKind::Tanh: return "tanhf(" + a + ")";
		case OpKind::Add: return a + " + " + b;
		case OpKind::Sub: return a + " - " + b;
		case OpKind::Mul: return a + " * " + b;
		case OpKind::Div: return a + " / " + b;
		default: return "/* unsupported op */ 0.0f";
	}
}

// How a kernel reads one input, given its shape and the output's shape.
struct Access {
	enum class Kind {
		Contiguous,  // the output's layout: element i
		Scalar,      // one value, loaded once before the loop
		Periodic,    // a suffix of the output's shape (e.g. a bias row): element i % period
		General,     // anything else: index math with constant divisors
	};
	Kind kind = Kind::Contiguous;
	std::size_t period = 0;
	std::string index;  // General: index expression in terms of i
};

Access classify(const Shape& in, const Shape& out) {
	const std::size_t n_in = num_elements(in);
	if (n_in == 1) return {Access::Kind::Scalar, 0, ""};
	if (n_in == num_elements(out)) return {Access::Kind::Contiguous, 0, ""};
	std::size_t lead = 0;
	while (lead < in.size() && in[lead] == 1) ++lead;
	const std::size_t rest = in.size() - lead;
	if (std::equal(in.begin() + static_cast<std::ptrdiff_t>(lead), in.end(), out.end() - static_cast<std::ptrdiff_t>(rest))) {
		return {Access::Kind::Periodic, n_in, ""};
	}

	// Sum over output dims of coord_d * stride_d, coord_d = (i / out_stride_d) % out_dim_d.
	const std::vector<std::int64_t> strides = broadcast_strides(in, out);
	std::vector<std::size_t> out_strides(out.size());
	std::size_t s = 1;
	for (std::size_t d=out.size(); d-- > 0;) {
		out_strides[d] = s;
		s *= static_cast<std::size_t>(out[d]);
	}
	std::string expr;
	for (std::size_t d=0; d<out.size(); ++d) {
		if (strides[d] == 0) continue;
		std::string coord = "i";
		if (out_strides[d] != 1) coord = "(i / " + std::to_string(out_strides[d]) + "u)";
		if (d > 0) coord = "(" + coord + " % " + std::to_string(out[d]) + "u)";  // the outermost coordinate never wraps
		const std::string term = strides[d] == 1 ? coord : coord + " * " + std::to_string(strides[d]) + "u";
		expr += (expr.empty() ? "" : " + ") + term;
	}
	return {Access::Kind::General, 0, expr};
}

}

FusedProgram single_op_program(OpKind op) {
	FusedProgram p;
	if (is_unary_elementwise(op)) {
		p.instrs = {FusedInstr::load(0), FusedInstr::unary(op, 0)};
	} else {
		p.instrs = {FusedInstr::load(0), FusedInstr::load(1), FusedInstr::binary(op, 0, 1)};
	}
	p.source_nodes = {op_name(op)};
	return p;
}

ElementwiseKernel generate_elementwise_kernel(const FusedProgram& program, const std::vector<Shape>& input_shapes,
                                              const Shape& out_shape, bool allow_vectorize) {
	std::vector<Access> access;
	for (const Shape& s : input_shapes) access.push_back(classify(s, out_shape));

	bool vectorized = allow_vectorize && num_elements(out_shape) % 4 == 0;
	for (const Access& a : access) {
		if (a.kind == Access::Kind::General) vectorized = false;
		if (a.kind == Access::Kind::Periodic && a.period % 4 != 0) vectorized = false;
	}

	// Immediates and loads of scalar inputs do not depend on the element.
	auto invariant = [&](const FusedInstr& ins) {
		return ins.kind == FusedInstr::Kind::Immediate ||
		       (ins.kind == FusedInstr::Kind::Load && access[static_cast<std::size_t>(ins.a)].kind == Access::Kind::Scalar);
	};
	auto reg = [](std::size_t r) { return "r" + std::to_string(r); };
	const std::size_t last = program.instrs.size() - 1;

	std::ostringstream os;
	os << "// Generated by minicompiler: " << program.num_ops() << " elementwise op(s)"
	   << (vectorized ? ", float4 accesses" : "") << ".\n"
	   << "extern \"C\" __global__ void __launch_bounds__(256)\n"
	   << kElementwiseKernelName << "(float* __restrict__ out";
	for (std::size_t k=0; k<input_shapes.size(); ++k) os << ", const float* __restrict__ in" << k;
	os << ", unsigned n)\n{\n";

	for (std::size_t r=0; r<program.instrs.size(); ++r) {
		const FusedInstr& ins = program.instrs[r];
		if (!invariant(ins)) continue;
		os << "\tconst float " << reg(r) << " = ";
		if (ins.kind == FusedInstr::Kind::Immediate) {
			os << float_literal(ins.immediate) << "\n";
		} else {
			os << "in" << ins.a << "[0];\n";
		}
	}
	os << "\tfor (unsigned i = blockIdx.x * blockDim.x + threadIdx.x; i < n; i += gridDim.x * blockDim.x) {\n";

	// The element-dependent instructions, with loads written by `load`.
	auto body = [&](const std::string& indent, auto&& load) {
		for (std::size_t r=0; r<program.instrs.size(); ++r) {
			const FusedInstr& ins = program.instrs[r];
			if (invariant(ins)) continue;
			os << indent << "const float " << reg(r) << " = ";
			switch (ins.kind) {
				case FusedInstr::Kind::Load: os << load(static_cast<std::size_t>(ins.a)); break;
				case FusedInstr::Kind::Unary: os << op_expr(ins.op, reg(static_cast<std::size_t>(ins.a)), ""); break;
				case FusedInstr::Kind::Binary:
					os << op_expr(ins.op, reg(static_cast<std::size_t>(ins.a)), reg(static_cast<std::size_t>(ins.b)));
					break;
				case FusedInstr::Kind::Immediate: break;
			}
			os << ";\n";
		}
	};

	if (!vectorized) {
		body("\t\t", [&](std::size_t k) {
			const Access& a = access[k];
			const std::string idx = a.kind == Access::Kind::Contiguous ? "i"
			                        : a.kind == Access::Kind::Periodic ? "i % " + std::to_string(a.period) + "u"
			                                                           : a.index;
			return "in" + std::to_string(k) + "[" + idx + "]";
		});
		os << "\t\tout[i] = " << reg(last) << ";\n";
	} else {
		// i counts groups of 4 elements. A periodic input's period is a multiple
		// of 4, so a group never straddles a repetition.
		for (const FusedInstr& ins : program.instrs) {
			if (ins.kind != FusedInstr::Kind::Load || invariant(ins)) continue;
			const Access& a = access[static_cast<std::size_t>(ins.a)];
			const std::string idx = a.kind == Access::Kind::Contiguous ? "i" : "i % " + std::to_string(a.period / 4) + "u";
			os << "\t\tconst float4 v" << ins.a << " = reinterpret_cast<const float4*>(in" << ins.a << ")[" << idx << "];\n";
		}
		os << "\t\tfloat4 o;\n";
		for (const char lane : {'x', 'y', 'z', 'w'}) {
			os << "\t\t{\n";
			body("\t\t\t", [&](std::size_t k) { return "v" + std::to_string(k) + "." + lane; });
			os << "\t\t\to." << lane << " = " << reg(last) << ";\n\t\t}\n";
		}
		os << "\t\treinterpret_cast<float4*>(out)[i] = o;\n";
	}
	os << "\t}\n}\n";
	return {os.str(), vectorized};
}

}
